AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template to deploy a private Alexa for Business skill with Salesforce integration.
Parameters:
  SalesforceInstanceUrl:
    Description: 'The service URL used to make Salesforce queries. If using My Domain, looks like this: https://<your-domain>.my.salesforce.com. If not using My Domains, looks like this: https://na50.salesforce.com/.'
    Type: String
  SkillID:
    Description: 'The Alexa Skill ID to restrict access to this Lambda. Note: this can be provided in the Lambda UI via function triggers too.'
    Type: String
    Default: ''
  VoiceCodeObjectName:
    Description: The name used to create the Voice Code object in Salesforce. Default is 'voice_code__c'.
    Type: String
    Default: 'voice_code__c'
  VoiceCodeFieldName:
    Description: The name used to create the Code field inside of the Voice Code object. Default is 'code__c'.
    Type: String
    Default: 'code__c'
Resources:
  AlexaSalesforceFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: 'A Lambda function that responds to Alexa requests and integrates with Salesforce. Created from https://github.com/alexa/alexa-for-business/tree/master/salesforce/skill-sample-nodejs-salesforce.'
      Environment:
        Variables:
          INSTANCE_URL: !Ref SalesforceInstanceUrl
          SKILL_ID: !Ref SkillID
          VOICE_CODE_OBJECT_NAME: !Ref VoiceCodeObjectName
          VOICE_CODE_FIELD_NAME: !Ref VoiceCodeFieldName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Salesforce_Skill
      MemorySize: 128
      Timeout: 3
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
  DynamoTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: Salesforce_Skill
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
